name: 'SWM GitHub Actions Basic'

on: push

jobs:
  first-job:
    name: 'First Job'

    runs-on: ubuntu-latest

    steps:
    - name: Send message to Webex space
      shell: bash
      run: |
        curl --location --request POST 'https://webexapis.com/v1/messages' \
        --header 'Authorization: Bearer ${{ secrets.WEBEX_TOKEN }}' \
        --header 'Content-Type: application/json' \
        --data-raw '{
          "roomId": "Y2lzY29zcGFyazovL3VybjpURUFNOnVzLXdlc3QtMl9yL1JPT00vNzk2N2JkYzAtZDM1Yi0xMWVkLThjYzEtYmZiN2YyMDEzMzc4",
          "text": "Message sent by GitHub Actions from ${{ github.repository }}"
        }'